markdown: kramdown
highlighter: rouge
permalink: blog/:year/:month/:day/:title.html
paginate: 6
paginate_path: page/:num

blog:
    name: bigBangRunner
    description: Web Software Engineer
    title: Web Software Engineer
    keywords: Web Software Engineer
    url: http://mybu.github.com
    # https://github.com/mybu/mybu.github.com
author:
    duoshuo: xuxp run
    name: xuxp run
    email: xuxp.run@outlook.com
    weibo: 2917650677
    github: xulao
    linkedin: chrispher-guan/5a/a68/6b8